### ISSUE TITLE
Azure deployment

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/hutch-bunny#9]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

A way to deploy Bunny quickly to Azure cloud infrastructure using Azure Container Apps.

### Acceptance Criteria

- [ ] Bunny can be configured, deployed to Azure with a guided Portal experience
- [ ] Specification of resources are configurable
-

### Tasks

- [ ] Bicep for creation
- [ ] Configurable configuration
- [ ] Add to docs

### Confirm creation

- [x] This issue is ready
